---
- name: "Add environment variables"
  shell: "echo 'Setting env vars'"
  environment:
    ENVIRONMENT: 'production'
    TYPEORM_CONNECTION: 'postgres'
    TYPEORM_MIGRATIONS_DIR: './src/migrations'
    TYPEORM_MIGRATIONS: './src/migrations'
    TYPEORM_ENTITIES: './modules/domain/**/*.entity{.ts,.js}'
    TYPEORM_HOST: 'udacity.cbv7959kpsjz.us-east-1.rds.amazonaws.com'
    TYPEORM_PORT: '5432'
    TYPEORM_USERNAME: 'postgres'
    TYPEORM_PASSWORD: 'strongP#ss12!!'
    TYPEORM_DATABASE: 'glee'

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Configure pm2"
  become: true
  shell: "sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu"