apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: webserver